import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackQuery from "@/app/utils/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eventparrot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQuery>{children}</TanstackQuery>
        {/* <script
          type="text/javascript"
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_PLACES}&libraries=places`}
        /> */}
      </body>
    </html>
  );
}
