import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Eventparrot",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <div>{children}</div>
    </section>
  );
}
